### PR TITLE
add ability to pass mask for context keys as well, in the shape of (b…

### PR DESCRIPTION
**Pull request by lucidrains**
…atch_size, context_keys_len)

### CODE REVIEW

**Comment by lucidrains** [comment]
@erickrf  if this looks good to you, i'll merge it!

**Comment by erickrf** [comment]
In principle it looks good. I'm working to automatically pad sequences when the length is not a multiple of batch size, and the masks accordingly. I intend to do a PR soon too.

**Comment by lucidrains** [comment]
@erickrf I've added auto-padding recently as well, I was running into the same issues https://github.com/lucidrains/reformer-pytorch/blob/master/README.md#additional-helpers

**Comment by lucidrains** [comment]
ok I'll double check some things and merge it later today, thank you!

**Pull request merged**
